// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2018 Datadog, Inc.

package config

// Group describes a group of options to display together
type Group struct {
	Name        string
	Priority    int      // Sections will be listed in ascending order
	Description string   // Short description of the section
	Options     []Option // Options will be listed in order
}

// Option describes a configuration option
type Option struct {
	// Common fields
	Name         string
	Default      interface{}
	Description  string
	Undocumented bool // For internal options not to expose in docs

	// datadog.yaml contents
	YAMLDesc    string // Defaults to Description if empty
	YAMLExample string // Autogenerated from Default if empty
	MergeDesc   bool   // Will ignore Description and just print the example

	// envvar bindings option
	NoEnvvar   bool   // Don't bind this option to an envvar
	EnvvarDesc string // Defaults to Description if empty
}

var configGroups []*Group

func registerGroup(g *Group) {
	configGroups = append(configGroups, g)
}

func GetGroups() []*Group {
	return configGroups
}
